export const INIT_FETCH_MOVIES = 'MOVIE:INIT_FETCH_MOVIES';
export const SEARCH_MOVIES = 'MOVIE:SEARCH_MOVIES';
export const UPLOAD_CACHE_MOVIES = 'MOVIE:UPLOAD_CACHE_MOVIES';
export const LOAD_CURRENT_MOVIE = 'MOVIE:LOAD_CURRENT_MOVIE';
export const LOAD_SIMILAR_MOVIES_BY_GENRE = 'MOVIE:LOAD_SIMILAR_BY_GENRE';
